version: "3"

services:
    backend:
        build:
            context: ./backend
        restart: always
        ports:
            - "8080:8080"
        env_file:
            - ./backend/.env
        depends_on:
            - db
        networks:
            - network

    db:
        image: postgres:alpine
        restart: always
        env_file:
            - ./backend/.env
        ports:
            - "5432:5432"
        networks:
            - network

networks:
    network:
        driver: bridge